services:
    vinny.giphy.controller.main:
        class: vinny\giphy\controller\main
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@language'
            - '@auth'

    vinny.giphy.listener:
        class: vinny\giphy\event\listener
        arguments:
            - '@config'
            - '@language'
            - '@template'
            - '@controller.helper'
        tags:
            - { name: event.listener }
